# Generated by Django 3.2.5 on 2021-09-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Art', 'Art'), ('Automotive & Powersports', 'Automotive & Powersports'), ('Beauty', 'Beauty'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Musical instruments', 'Musical instruments'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports', 'Sports'), ('Tools', 'Tools'), ('Toys & Games', 'Toys & Games'), ('Watches', 'Watches'), ('Other', 'Other')], max_length=100),
        ),
    ]
