# Generated by Django 3.2.5 on 2021-09-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20210907_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Art', 'Art'), ('Automotive & Powersports', 'Automotive & Powersports'), ('Beauty', 'Beauty'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Musical instruments', 'Musical instruments'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports', 'Sports'), ('Tools', 'Tools'), ('Toys & Games', 'Toys & Games'), ('Watches', 'Watches'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
